### ISSUE TITLE
Add support for shield mounted ds18b20

### ISSUE THREAD

**Issue by n1md4** [arthurrump/esphome-opentherm#9]
Add support for shield mounted ds18b20 temperature sensor.  Marked T on the OpenTherm Master Shield.

**Comment by arthurrump** [comment]
I don't think there are any changes needed in this component to support that. You can already add the [Dallas sensor](https://esphome.io/components/sensor/dallas.html) to the configuration and use that as the sensor in the pid climate (for example).

Sidenote: I have tried using the shield mounted sensor, but since my "thermostat" (the ESP8266 and shield running ESPHome with this component) is now located next to the boiler, the readings weren't actually that useful to me. I instead scattered a few inexpensive zigbee thermometers throughout the house, so that we no longer run the heater based on the temperature in just one room.

**Comment by n1md4** [comment]
Thanks you for the information.  I'll take the opportunity to thank you for creating this module too, works incredibly well.  Very much appreciated.
